# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Yeonju Lee a.k.a. Lindsey
email: lindsey.lee@berkeley.edu
description: > # this means to ignore newlines until "baseurl:"
  Interested in Data science, Applied statistics, and Violin :)
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lindsey-lee.github.io" # the base hostname & protocol for your site
twitter_username: lindsey1_lee
github_username:  lindsey-lee

# Build settings
markdown: kramdown
